name: Resize Auto Scaling Group

on:
  workflow_dispatch:
    inputs:
      desired_capacity:
        description: 'New desired capacity'
        required: true
      minimum_capacity:
        description: 'Minimum size of the Auto Scaling Group'
        required: true
      maximum_capacity:
        description: 'Maximum size of the Auto Scaling Group'
        required: true
      port_context:
        required: true
        description: 'Port workflow context (entity)'
        type: string

jobs:
  resize-asg:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Resize Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name ${{ fromJson(inputs.port_context).entity.title }} \
            --desired-capacity ${{ github.event.inputs.desired_capacity }} \
            --min-size ${{ github.event.inputs.minimum_capacity }} \
            --max-size ${{ github.event.inputs.maximum_capacity }}
